"""empty message

Revision ID: f4897e540830
Revises: 
Create Date: 2022-11-24 15:29:35.768919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4897e540830'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DATA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.String(length=100), nullable=False),
    sa.Column('ChannellD', sa.String(length=100), nullable=False),
    sa.Column('circle', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('datetim', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobile_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('customer_call_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('previous_mobile_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MobileNumber', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('total_gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift', sa.String(length=100), nullable=False),
    sa.Column('gift_qantity', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=55), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('passsword', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('total_gift')
    op.drop_table('previous_mobile_numbers')
    op.drop_table('mobile_number')
    op.drop_table('DATA')
    # ### end Alembic commands ###
